### ISSUE TITLE
Can't use new template AzureTemplate.v5.tb7 

### ISSUE THREAD

**Issue by Tejpandya** [AzureArchitecture/threat-model-templates#9]
Hello,

I'm Using Microsoft Threat Modeling Tool 7.3.20120.2.

When I'm trying to select This template  **AzureTemplate.v5.tb7**  to create a TM. Im getting this below errror.

![image](https://user-images.githubusercontent.com/23713711/177494590-fa097258-0c63-4a2d-940f-f4261b01cfe2.png)

Upon veriying error log . Stacktrace is 

`Threat Modeling Tool, Assembly version 'TMT7, Version=7.3.20120.2, Culture=neutral, PublicKeyToken=69c3241e6f0468ca', today is 'Wednesday, July 6, 2022 12:50:38 PM'Exception information:
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderStandaloneKnowledgeBase.Read22_KnowledgeBase()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at ThreatModeling.ExternalStorage.KB.StandaloneKnowledgeBase.InitializeKnowledgeBaseFromDir(String filePath)
   at ThreatModeling.Model.KnowledgeBaseModel.InitializeFromStandaloneKb(String ThreatBaseDir)
   at ThreatModeling.Model.ObjectModel.CreateBase(Boolean openDesignMode, String loadFromFilePath, Boolean browseThreatBase)
   at ThreatModeling.Model.ObjectModel..ctor(String loadFromFilePath, Boolean openDesignMode, Boolean IsThreatBase, Boolean browseThreatBase)
   at ThreatModeling.ViewModel.DashboardViewModel.BrowseThreatBase(String fileName)
   at ThreatModeling.ViewModel.BrowseThreatBaseCommand.OpenFile(String fileName)
   at ThreatModeling.ViewModel.BrowseThreatBaseCommand.ExecuteImp(Object parameter)
   at ThreatModeling.ViewModel.Commands.TrackedCommand.Execute(Object parameter)`
   
   
   
Any solution or workaround for this issue ?

Thanks

**Comment by PatrickGallucci** [comment]
Resolved

**Comment by Tejpandya** [comment]
hello @PatrickGallucci  

I have downloaded the new Template. Still facing the same issue .

Using the TM Tool version : **7.3.20120.2**
 Getting the same exception "For security reasons DTD is prohibited in this XML document."
